# Definição de variáveis (ambiente “local” do REST Client)
@base_url = https://vigilant-halibut-gg5975r6q9xh9xvx-8080.app.github.dev

### Inserir nova veiculo
POST {{ base_url }}/api/veiculos
Content-Type: application/json

{
  "nome": "Golf",
  "modelo": "Gti",
  "quantidade": 10,
  "valor": 50000
}

### Listar todas as veiculos
GET {{ base_url }}/api/veiculos
Accept: application/json

### Buscar veiculo por ID
GET {{ base_url }}/api/veiculos/3
Accept: application/json

### Atualizar veiculo (PUT)
PUT {{ base_url }}/api/veiculos/1
Content-Type: application/json

{
  "nome": "Gol",
  "modelo": "Gti"
  "quantidade": 10
  valor: 50000
}

### Remover veiculo (DELETE)
DELETE {{ base_url }}/api/veiculos/1
Accept: */*